spring.application.name=ApiGateway
server.port=8080

spring.cloud.gateway.server.webflux.routes[0].id=usuario-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/usuarios/**

spring.cloud.gateway.server.webflux.routes[1].id=catalogo-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/videojuegos/**

spring.cloud.gateway.server.webflux.routes[2].id=carro-service
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8083
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/carrito/**

spring.cloud.gateway.server.webflux.routes[3].id=gestion-service
spring.cloud.gateway.server.webflux.routes[3].uri=http://localhost:8084
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/pedidos/**

spring.cloud.gateway.server.webflux.routes[4].id=pagos-service
spring.cloud.gateway.server.webflux.routes[4].uri=http://localhost:8085
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/pagos/**

spring.cloud.gateway.server.webflux.routes[5].id=coleccion-service
spring.cloud.gateway.server.webflux.routes[5].uri=http://localhost:8086
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/coleccion/**

spring.cloud.gateway.server.webflux.routes[6].id=notificaciones-service
spring.cloud.gateway.server.webflux.routes[6].uri=http://localhost:8087
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/notificaciones/**